# Generated by Django 5.2.6 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField()),
                ('country', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=20)),
                ('center_freq', models.FloatField()),
                ('airport_codes', models.CharField(max_length=80)),
            ],
        ),
    ]
