# Generated by Django 5.2.6 on 2025-11-28 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='airport_codes',
        ),
        migrations.AddField(
            model_name='recording',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 28, 16, 9, 47, 363424, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
