# Generated by Django 5.2.6 on 2025-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_recording_airport_codes_recording_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='airport_codes',
            field=models.CharField(default='LKTB', max_length=80),
            preserve_default=False,
        ),
    ]
