# Generated by Django 5.2.6 on 2025-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_recording_airport_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
