# Generated by Django 5.2.6 on 2025-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_recording_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='snr',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
    ]
