# Generated by Django 5.2.6 on 2026-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_recording_snr'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
