# Generated by Django 5.2.6 on 2026-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_recording_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='transcript',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
