# Generated by Django 5.2.6 on 2026-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_recording_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField()),
                ('job_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
