# Generated by Django 5.2.6 on 2026-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_transcripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField()),
                ('reason', models.CharField(choices=[('empty_file', 'Empty file'), ('snr', 'SNR threshold'), ('short', 'Audio too short'), ('long', 'Audio too long'), ('user', 'User deleted'), ('unk', 'Unknown')], default='unk', max_length=30)),
                ('snr_thres', models.FloatField()),
                ('short_limit', models.FloatField()),
                ('long_limit', models.FloatField()),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
