# Generated by Django 5.2.6 on 2026-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='freq',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
