# Generated by Django 5.2.6 on 2026-04-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_recording_code_recording_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted',
            name='long_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='short_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='snr_thres',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
