services:
  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    restart: no
  django-web:
    build: .
    volumes:
      - .:/app
      - shared:/app/shared
# -----------------------------------
#     If you want to use a different directory, change only the part before :
#     Input file directory
      - ./records:/data/in
#     Output files directory
      - ./audio_files:/data/out
# -----------------------------------
      - ./scripts:/scripts
      - ./exports:/data/export
    container_name: django-docker
    ports:
      - "10000:10000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    depends_on:
      - migrate

  pipeline:
    build: .
    command: python /app/scripts/pipeline.py
    volumes:
      - .:/app
      - shared:/app/shared
# -----------------------------------
#     If you want to use a different directory, change only the part before :
#     Input file directory
      - ./records:/data/in
#     Output files directory
      - ./audio_files:/data/out
# -----------------------------------
      - ./scripts:/scripts
    container_name: pipeline
    restart: unless-stopped
    depends_on:
      - django-web
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  shared:
